### ISSUE TITLE
People are not freed until they actually log on, even if should be free

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/ExilePearl#33]
For example, if I'm altbanned, and my pearled alt has their pearl destroyed, then I should be able to log on now on my other alts, but I can't. Not until that alt logs in, and the system goes "OH SHIT wait, you're free!" thus unlocking the altban.

You should ideally be able to log on as soon as that pearl is destroyed. Extra hoops are not just annoying but newer players might not realize they can even do that, and may just give up and leave.

**Comment by Lazersmoke** [comment]
What message are you kicked with? 

    You are banned, message modmail if you think this is an error
or

    You have too many imprisoned alts, message modmail if you think this is an error.
?

**Comment by GavJenks** [comment]
Imprisoned alts

**Comment by KaloHG** [comment]
Hey this is an issue I relate to a lot. Anyway, I'll begin working on this tonight but a bit differently than what the issue describes. I intend on just modifying the BanstickListener to include a check to see if the pearl being referenced was freed offline, which should resolve this bug effectively, as even though the pearl will still exist, it shouldn't stop anything as other alts will be able to login since the pearl is "freed".

**Comment by KaloHG** [comment]
Should be good to go, 👍
