### ISSUE TITLE
There is no way to upgrade pearls as a player

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/ExilePearl#52]

**Comment by KaloHG** [comment]
While this can be done via the crafting table menu like refueling is done, however since essence is utilized to refuel pearls, I don't believe it could be used to upgrade. I think it'd be easier just to have it so you can make an "upgrade material" in a factory of some sort, that takes the mana cost and instead have that be the upgrade material. This would be the simple and easy method that I could do for you. Or you could do the hard thing and make a new command in EssenceGlue that allows you to run /ep upgrade and eats the mana that way.

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/ExilePearl/pull/67
